# Generated by Django 6.1.1 on 2026-09-16 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocation", "0001_initial"),
        ("pools", "0003_balanceimportbatch_dailybalance"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("value_date", models.DateField()),
                ("gross_income", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "direct_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "distributable_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "total_weighted_funds",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "depositor_pool_share",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("mudarib_share", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[("simulated", "Simulated"), ("signed", "Signed")],
                        default="simulated",
                        max_length=20,
                    ),
                ),
                (
                    "calculation_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_runs",
                        to="pools.pool",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AllocationLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("participant_class", models.CharField(max_length=100)),
                ("daily_funds", models.DecimalField(decimal_places=2, max_digits=18)),
                ("weightage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "weighted_funds",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "allocation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="allocation.allocationrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
