# Generated by Django 6.1.1 on 2026-09-16 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocation", "0002_allocationrun_allocationline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationrun",
            name="checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checked_allocation_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="allocationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("simulated", "Simulated"),
                    ("pending_approval", "Pending Approval"),
                    ("signed", "Signed"),
                    ("rejected", "Rejected"),
                ],
                default="simulated",
                max_length=20,
            ),
        ),
    ]
