# Generated by Django 6.1.1 on 2026-09-16 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "allocation",
            "0003_allocationrun_checked_at_allocationrun_checked_by_and_more",
        ),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositorStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("participant_class", models.CharField(max_length=100)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "net_deposits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "profit_allocated",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("narrative", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="allocation.allocationrun",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
