# Generated by Django 5.2.17 on 2026-09-19 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocation", "0004_depositorstatement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationrun",
            name="shariah_review_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="shariah_signed_off_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="shariah_signed_off_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shariah_signed_off_allocation_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="allocationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("simulated", "Simulated"),
                    ("pending_approval", "Pending Approval"),
                    ("shariah_review", "Shariah Review"),
                    ("signed", "Signed"),
                    ("rejected", "Rejected"),
                ],
                default="simulated",
                max_length=20,
            ),
        ),
    ]
