# Generated by Django 5.2.17 on 2026-09-29 08:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocation", "0005_allocationrun_shariah_review_note_and_more"),
        ("pools", "0004_pool_pending_approval"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationrun",
            name="is_restatement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="replaces_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restatements",
                to="allocation.allocationrun",
            ),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="restatement_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="allocationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("simulated", "Simulated"),
                    ("pending_approval", "Pending Approval"),
                    ("shariah_review", "Shariah Review"),
                    ("signed", "Signed"),
                    ("rejected", "Rejected"),
                    ("reversed", "Reversed"),
                ],
                default="simulated",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReservePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reserve_type",
                    models.CharField(
                        choices=[
                            ("per", "Profit Equalization Reserve"),
                            ("irr", "Investment Risk Reserve"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "rate_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2.00"), max_digits=5
                    ),
                ),
                (
                    "cap_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserve_policies",
                        to="pools.pool",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pool", "reserve_type"),
                        name="unique_reserve_type_per_pool",
                    )
                ],
            },
        ),
    ]
