# Generated by Django 6.1.1 on 2026-10-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocation", "0006_allocationrun_is_restatement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationrun",
            name="config_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="irr_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="is_loss",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="per_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="rounding_residual",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
