# Generated by Django 6.1.1 on 2026-10-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocation", "0007_allocationrun_config_snapshot_and_more"),
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationline",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocation_lines",
                to="participants.participantaccount",
            ),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="depositorstatement",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statements",
                to="participants.participantaccount",
            ),
        ),
    ]
