# Generated by Django 6.1.1 on 2026-10-10 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "allocation",
            "0008_allocationline_account_allocationrun_period_start_and_more",
        ),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutBatchRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("batch_code", models.CharField(max_length=100)),
                ("status", models.CharField(default="draft", max_length=30)),
                ("payload", models.JSONField(default=dict)),
                (
                    "allocation_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_batch",
                        to="allocation.allocationrun",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
