# Generated by Django 5.2.17 on 2026-09-29 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_incomeexpenseevent"),
        ("pools", "0004_pool_pending_approval"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("reconciliation_date", models.DateField()),
                (
                    "source_system",
                    models.CharField(default="Core Banking CBS / GL", max_length=100),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("matched_records", models.IntegerField(default=0)),
                ("exception_count", models.IntegerField(default=0)),
                (
                    "variance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("variance_flagged", "Variance Flagged"),
                            ("cleared", "Cleared"),
                        ],
                        default="matched",
                        max_length=20,
                    ),
                ),
                (
                    "control_total_status",
                    models.CharField(default="BalancedPASS", max_length=20),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_batches",
                        to="pools.pool",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-reconciliation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("account_reference", models.CharField(max_length=100)),
                ("cbs_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("gl_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("variance", models.DecimalField(decimal_places=2, max_digits=18)),
                ("status", models.CharField(default="matched", max_length=20)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accounting.reconciliationbatch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
