# Generated by Django 6.1.1 on 2026-10-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_reconciliationbatch_reconciliationitem"),
        ("allocation", "0006_allocationrun_is_restatement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalbatch",
            name="allocation_run",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_batch",
                to="allocation.allocationrun",
            ),
        ),
    ]
