# Generated by Django 6.1.1 on 2026-10-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_alter_journalbatch_allocation_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomeexpenseevent",
            name="bank_absorbed_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="incomeexpenseevent",
            name="cost_classification",
            field=models.CharField(
                choices=[
                    ("direct_permissible", "Direct Operating Expense (Permissible)"),
                    ("indirect_overhead", "Indirect Overhead (Bank Absorbed)"),
                    ("permissible_income", "Permissible Pool Income"),
                    (
                        "non_permissible_income",
                        "Non-Permissible Income (Charity Quarantine)",
                    ),
                ],
                default="direct_permissible",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="incomeexpenseevent",
            name="is_direct_expense",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="incomeexpenseevent",
            name="is_overhead_leakage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incomeexpenseevent",
            name="pool_chargeable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="incomeexpenseevent",
            name="quarantined_to_charity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incomeexpenseevent",
            name="shariah_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
