# Generated by Django 6.1.1 on 2026-10-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_incomeexpenseevent_bank_absorbed_amount_and_more"),
        ("allocation", "0007_allocationrun_config_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalbatch",
            name="reverses_batch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_by",
                to="accounting.journalbatch",
            ),
        ),
        migrations.AlterField(
            model_name="journalbatch",
            name="allocation_run",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_batch",
                to="allocation.allocationrun",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="accounting.journalbatch",
            ),
        ),
    ]
