# Generated by Django 5.2.17 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0002_purificationentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exceptioncase",
            name="source_module",
            field=models.CharField(
                choices=[
                    ("accounting", "Accounting"),
                    ("allocation", "Allocation"),
                    ("balance_import", "Balance Import"),
                    ("pool_lifecycle", "Pool Lifecycle"),
                    ("asset_assignment", "Asset Assignment"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]