# Generated by Django 5.2.17 on 2026-09-18 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0003_alter_exceptioncase_source_module"),
        ("pools", "0003_balanceimportbatch_dailybalance"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedPartyTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("related_party_name", models.CharField(max_length=255)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("director", "Director"),
                            ("shareholder", "Shareholder"),
                            ("family_member", "Family Member"),
                            ("affiliate_company", "Affiliate Company"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("transaction_type", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("transaction_date", models.DateField()),
                (
                    "disclosure_status",
                    models.CharField(
                        choices=[
                            ("disclosed", "Disclosed"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("flagged", "Flagged"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_party_transactions",
                        to="pools.pool",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_related_party_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
