# Generated by Django 5.2.17 on 2026-09-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0004_relatedpartytransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="exceptioncase",
            name="investigation_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exceptioncase",
            name="treatment_plan",
            field=models.TextField(blank=True, null=True),
        ),
    ]
