# Generated by Django 6.1.1 on 2026-10-10 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pools", "0005_periodclosechecklist"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("reference", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=255)),
                ("participant_class", models.CharField(max_length=100)),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("cnic_ntn", models.CharField(blank=True, default="", max_length=30)),
                ("iban", models.CharField(blank=True, default="", max_length=34)),
                ("bank_name", models.CharField(blank=True, default="", max_length=100)),
                ("bic", models.CharField(blank=True, default="", max_length=11)),
                (
                    "tax_status",
                    models.CharField(
                        choices=[("filer", "Filer"), ("non_filer", "Non-Filer")],
                        default="filer",
                        max_length=10,
                    ),
                ),
                ("zakat_exempt", models.BooleanField(default=False)),
                (
                    "default_channel",
                    models.CharField(
                        choices=[
                            ("raast", "Raast"),
                            ("one_link", "1LINK"),
                            ("ibt", "Inter-branch transfer"),
                        ],
                        default="raast",
                        max_length=10,
                    ),
                ),
                (
                    "nominee_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("account_number", models.CharField(max_length=50)),
                ("opened_date", models.DateField()),
                ("closed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="participants.participant",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participant_accounts",
                        to="pools.pool",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["account_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reference"),
                name="unique_participant_reference_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="participantaccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "account_number"),
                name="unique_account_number_per_tenant",
            ),
        ),
    ]
