# Generated by Django 5.2.17 on 2026-09-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("ur", "Urdu")], default="en", max_length=2
            ),
        ),
    ]
