import { useState } from "react"

export interface WaterfallStep {
  label: string
  amount: number
  type: "addition" | "deduction" | "subtotal" | "final"
  description?: string
  percentage?: number
}

export interface ProfitWaterfallChartProps {
  grossIncome: number
  directExpenses: number
  distributable: number
  mudaribShare: number
  depositorShare: number
  mudaribRatio?: number
  currency?: string
}

export function ProfitWaterfallChart({
  grossIncome,
  directExpenses,
  distributable,
  mudaribShare,
  depositorShare,
  mudaribRatio = 20,
  currency = "PKR",
}: ProfitWaterfallChartProps) {
  const [hoveredIdx, setHoveredIdx] = useState<number | null>(null)

  const steps: WaterfallStep[] = [
    {
      label: "Gross Income",
      amount: grossIncome,
      type: "addition",
      description: "Total recognized revenue generated by pool assets",
    },
    {
      label: "Direct Expenses",
      amount: directExpenses,
      type: "deduction",
      description: "Direct asset costs, takaful, and allowable operational fees",
      percentage: grossIncome > 0 ? (directExpenses / grossIncome) * 100 : 0,
    },
    {
      label: "Net Distributable",
      amount: distributable,
      type: "subtotal",
      description: "Net profit available for Mudarib / Rab-ul-Mal distribution",
      percentage: grossIncome > 0 ? (distributable / grossIncome) * 100 : 0,
    },
    {
      label: `Mudarib Share (${mudaribRatio}%)`,
      amount: mudaribShare,
      type: "deduction",
      description: "Bank management fee as agreed in Mudarabah contract",
      percentage: distributable > 0 ? (mudaribShare / distributable) * 100 : 0,
    },
    {
      label: `Depositor Pool (${100 - mudaribRatio}%)`,
      amount: depositorShare,
      type: "final",
      description: "Final net profit allocated across all depositor tiers",
      percentage: distributable > 0 ? (depositorShare / distributable) * 100 : 0,
    },
  ]

  const maxVal = Math.max(grossIncome, distributable, 1)

  return (
    <div className="w-full space-y-4 overflow-hidden rounded-lg border border-white/8 bg-navy-900/50 p-4">
      <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0 flex-1">
          <h4 className="text-xs font-semibold uppercase tracking-wider text-ink-secondary truncate">
            Shariah Profit Distribution Waterfall
          </h4>
          <p className="text-[11px] text-ink-muted truncate">
            Auditable cascade from Gross Pool Income to Net Depositor Allocation
          </p>
        </div>
        <div className="flex shrink-0 items-center gap-3 text-[11px]">
          <span className="flex items-center gap-1.5">
            <span className="h-2 w-2 rounded-full bg-emerald-500" />
            <span className="text-ink-secondary">Inflow</span>
          </span>
          <span className="flex items-center gap-1.5">
            <span className="h-2 w-2 rounded-full bg-rose-400" />
            <span className="text-ink-secondary">Deduction</span>
          </span>
          <span className="flex items-center gap-1.5">
            <span className="h-2 w-2 rounded-full bg-sky-400" />
            <span className="text-ink-secondary">Net Pool</span>
          </span>
        </div>
      </div>

      {/* Waterfall Visual Bars */}
      <div className="space-y-2.5 pt-2">
        {steps.map((step, idx) => {
          const widthPct = Math.min(100, Math.max(3, (step.amount / maxVal) * 100))
          const isHovered = hoveredIdx === idx

          const barColor =
            step.type === "addition"
              ? "bg-gradient-to-r from-emerald-600 to-emerald-400"
              : step.type === "deduction"
              ? "bg-gradient-to-r from-rose-600 to-rose-400"
              : step.type === "subtotal"
              ? "bg-gradient-to-r from-teal-600 to-teal-400"
              : "bg-gradient-to-r from-sky-600 to-emerald-400"

          return (
            <div
              key={step.label}
              className={`relative rounded-md p-2 transition-all cursor-pointer overflow-hidden ${
                isHovered ? "bg-white/5" : "hover:bg-white/3"
              }`}
              onMouseEnter={() => setHoveredIdx(idx)}
              onMouseLeave={() => setHoveredIdx(null)}
            >
              <div className="flex items-center justify-between gap-2 text-xs mb-1.5">
                <div className="flex min-w-0 flex-1 items-center gap-2">
                  <span className="font-semibold text-ink-primary truncate">{step.label}</span>
                  {step.percentage !== undefined && (
                    <span className="shrink-0 rounded bg-white/5 px-1.5 py-0.5 font-mono text-[10px] text-ink-muted">
                      {step.percentage.toFixed(1)}%
                    </span>
                  )}
                </div>
                <span
                  className={`shrink-0 font-mono font-bold text-xs pl-2 ${
                    step.type === "deduction" ? "text-rose-400" : "text-emerald-400"
                  }`}
                >
                  {step.type === "deduction" ? "-" : ""}
                  {currency} {step.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                </span>
              </div>

              {/* Bar track */}
              <div className="h-2.5 w-full rounded-full bg-navy-950/80 overflow-hidden border border-white/5">
                <div
                  className={`h-full rounded-full transition-all duration-500 shadow-sm ${barColor}`}
                  style={{ width: `${widthPct}%` }}
                />
              </div>

              {step.description && (
                <p className="mt-1 text-[10px] text-ink-muted truncate">{step.description}</p>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
