# Generated by Django 6.1.1 on 2026-10-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
        ("pools", "0005_periodclosechecklist"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailybalance",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="daily_balances",
                to="participants.participantaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="dailybalance",
            index=models.Index(
                fields=["pool", "value_date"], name="dailybal_pool_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailybalance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", False)),
                fields=("pool", "value_date", "account"),
                name="unique_daily_balance_per_account_per_day",
            ),
        ),
    ]
