# Generated by Django 6.1.1 on 2026-10-06 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0003_circleproposal_circlevote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="biometric_auth_ref",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="ceremony_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="recipient_bank",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="recipient_iban",
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="secondary_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="secondary_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="counter_approved_payouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="settlement_rail",
            field=models.CharField(
                choices=[
                    ("raast_rtgs", "Raast Real-Time P2P/P2B (Instant Settlement)"),
                    ("onelink_ips", "1LINK Inter-bank Funds Transfer (1IBFT)"),
                    ("internal_book", "Internal Islamic Branch Transfer"),
                ],
                default="raast_rtgs",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="settlement_utr",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="shariah_certificate_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="shariah_compliance_status",
            field=models.CharField(default="certified_qard_hasana", max_length=40),
        ),
    ]
