# Generated by Django 5.2.17 on 2026-09-28 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shariahdecision",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shariahdecision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_shariah_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shariahdecision",
            name="decision_type",
            field=models.CharField(
                choices=[
                    ("product_approval", "Product Approval"),
                    ("policy_ruling", "Policy Ruling"),
                    ("annual_review", "Annual Review"),
                    ("purification_directive", "Purification Directive"),
                    ("exemption", "Exemption"),
                ],
                default="product_approval",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="shariahdecision",
            name="document_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="shariahdecision",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shariahdecision",
            name="fatwa_arabic_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shariahdecision",
            name="fiqh_reference",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shariahdecision",
            name="mandatory_caveats",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shariahdecision",
            name="meeting_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shariahdecision",
            name="scholars_signatories",
            field=models.TextField(blank=True, null=True),
        ),
    ]
