# Generated by Django 5.2.17 on 2026-09-29 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_shariahdecision_approved_at_and_more"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JurisdictionRulePack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(default="2025.01", max_length=20)),
                ("effective_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("rules_config", models.JSONField(default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "code", "version"),
                        name="unique_rulepack_version_per_tenant",
                    )
                ],
            },
        ),
    ]
