# Generated by Django 6.1.1 on 2026-10-05 08:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_jurisdictionrulepack"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShariahQuorumVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("scholar_name", models.CharField(max_length=255)),
                ("scholar_title", models.CharField(max_length=150)),
                (
                    "decision_vote",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("abstain", "Abstain"),
                        ],
                        default="approve",
                        max_length=20,
                    ),
                ),
                ("fiqh_concurrence_notes", models.TextField(blank=True, default="")),
                ("digital_signature_hash", models.CharField(max_length=64)),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quorum_votes",
                        to="products.shariahdecision",
                    ),
                ),
                (
                    "signatory_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["voted_at"],
            },
        ),
    ]
